{{- if .Values.rasterCommon.authentication.opa.enabled }}
{{- $chartName := include "mapproxy.name" . -}}
{{- $releaseName := .Release.Name -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $releaseName }}-envoy
data:
  envoy.yaml: |-
{{ tpl (.Files.Get "config/envoy.yaml") . | indent 4 }}
{{- end }}
