{{- $releaseName := .Release.Name -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $serviceName := include "service.fullname" . -}}
{{- if and (.Values.mapproxy.enabled) (.Values.mapproxy.ingress.enabled) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if eq .Values.mapproxy.ingress.type "nginx-org" }}
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: 'serviceName={{ $serviceName }} rewrite=/'
    {{- end }}
    {{- if eq .Values.mapproxy.ingress.type "nginx-kubernetes" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- end }}   
    nginx.org/location-snippets: |
      proxy_set_header 'X-Script-Name' '{{ .Values.mapproxy.ingress.path }}';
spec:
{{- if .Values.mapproxy.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.mapproxy.ingress.host | quote }}
    secretName: ingress-tls-secret
  {{- end }}
  rules:
  - http:
      paths:
      - path: {{ .Values.mapproxy.ingress.path }}{{- if eq .Values.mapproxy.ingress.type "nginx-kubernetes" }}(.*){{- end }}
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}-nginx
            port:
              number: {{ .Values.nginx.port }}
    host: {{ .Values.mapproxy.ingress.host | quote }}
{{- end -}}
