{{- if .Values.mapproxy.enabled -}}
{{- $chartName := include "mapproxy.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: {{ .Release.Name }}-{{ $chartName }}
    component: map-proxy-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  S3_ENDPOINT_URL: {{ .Values.rasterCommon.storage.s3.endpointUrl | quote }}
  S3_BUCKET:  {{ .Values.rasterCommon.storage.s3.tilesBucket | quote }}
  AWS_HTTPS: {{ .Values.rasterCommon.storage.s3.awsHttps | quote }}
  TELEMETRY_TRACING_ENABLED: {{ .Values.global.tracing.enabled | quote }}
  TELEMETRY_TRACING_ENDPOINT: {{ .Values.global.tracing.url | quote }}
  CORS_ENABLED: {{ .Values.mapproxy.env.cors.enabled | quote }}
  CORS_ALLOWED_HEADERS: {{ template "map-proxy.cors.allowedHeaders" . }}
  CORS_ALLOWED_ORIGIN: {{ .Values.mapproxy.env.cors.allowedOrigin | quote }}
  AUTH_ENABLED: {{ .Values.mapproxy.env.authentication.WMS.enabled | quote }}
  AUTH_VALID_DOMAIN: {{ .Values.mapproxy.env.authentication.WMS.requiredDomain | quote }}
  AUTH_HEADER_NAME: {{ default .Values.rasterCommon.authentication.opa.customHeaderName .Values.mapproxy.env.authentication.token.headerNameOverride | quote }}
  AUTH_QUERY_NAME: {{ .Values.mapproxy.env.authentication.token.queryName | quote }}
{{- end }}
