{{- if .Values.nginx.enabled -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-nginx-configmap
  labels:
    app: {{ $releaseName }}-{{ $chartName }}
    component: nginx-configmap
    environment: {{ .Values.environment }}
    release: {{ $releaseName }}
data:
  NGINX_CONFIG: {{ tpl (.Files.Get "config/nginx.conf") . | quote }}
  NGINX_ROOT_CONFIG: {{ .Files.Get "config/nginx_root.conf" | quote }}
  NGINX_MAPPROXY_CONFIG: {{ tpl (.Files.Get "config/nginx.mapproxy.conf") . | quote }}
  NGINX_MAPPROXY_WMTS_CONFIG: {{ tpl (.Files.Get "config/nginx.mapproxy.wmts.conf") . | quote }}
{{- end }}
