{{- $releaseName := .Release.Name -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $cloudProviderFlavor := include "mapproxy.cloudProviderFlavor" . -}}
{{- $serviceName := include "service.fullname" . -}}
{{ $targetPort := ternary "external" "internal" .Values.rasterCommon.authentication.opa.enabled }}

{{- if and (and (.Values.mapproxy.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.mapproxy.route.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $releaseName }}-route
  annotations:
    {{- if .Values.mapproxy.route.timeout.enabled }}
    haproxy.router.openshift.io/timeout: {{ .Values.mapproxy.route.timeout.duration }}
    {{- end }}
spec:
  {{- if .Values.mapproxy.route.host }}
  host: {{ .Values.mapproxy.route.host }}
  {{- end }}
  path:  {{ .Values.mapproxy.route.path | default "/" }}
  port:
    targetPort: {{ $targetPort }}
  to:
    kind: Service
    name: {{ $serviceName }}-nginx
  {{- if .Values.mapproxy.route.https }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- if .Values.mapproxy.route.useCert }}
    certificate: {{ .Files.Get "config/cert.pem" | quote }}
    key: {{ .Files.Get "config/key.pem" | quote }}
    caCertificate: {{ .Files.Get "config/caCertificate.pem" | quote }}
    {{- end }}
  {{- end -}}
{{- end -}}
