{{- if .Values.mapproxy.enabled -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-init-configmap
  labels:
    app: {{ $releaseName }}-{{ $chartName }}
    component: init-container-configmap
    environment: {{ .Values.environment }}
    release: {{ $releaseName }}
data:
  LOG_LEVEL: {{ .Values.initContainer.env.logLevel | quote }}
  CONFIG_PROVIDER: {{ .Values.rasterCommon.storage.mapproxyConfigProvider | quote }}
  S3_ENDPOINT_URL: {{ .Values.rasterCommon.storage.s3.endpointUrl | quote }}
  S3_BUCKET: {{ .Values.rasterCommon.storage.s3.tilesBucket | quote }}
  S3_SSL_ENABLED: {{ .Values.rasterCommon.storage.s3.sslEnabled | quote }}
  DB_HOST: {{ .Values.rasterCommon.db.host | quote }}
  DB_NAME: {{ .Values.rasterCommon.db.name | quote }}
  DB_SCHEMA: {{ .Values.mapproxy.db.schema | quote }}
  DB_PORT: {{ .Values.rasterCommon.db.port | quote }}
  DB_SSL_ENABLE: {{ .Values.rasterCommon.db.sslEnabled | quote }}
  DB_SSL_REJECT_UNAUTHORIZED: {{ .Values.rasterCommon.db.rejectUnauthorized | quote }}
  DB_SSL_PATH_CA: {{ .Values.initContainer.env.ssl.CA_FILE_LOCATION }}
  DB_SSL_PATH_KEY: {{ .Values.initContainer.env.ssl.KEY_FILE_LOCATION }}
  DB_SSL_PATH_CERT: {{ .Values.initContainer.env.ssl.CERT_FILE_LOCATION }}
  UWSGI_INI: {{ tpl (.Files.Get "config/mapProxyUwsgi.ini") . | quote }}
  LOG_INI: {{ tpl (.Files.Get "config/log.ini") . | quote }}
{{- end }}
