apiVersion: v2
name: mapproxy
description: A Helm chart for mapproxy service
type: application
version: 1.5.7
appVersion: 1.5.7
dependencies:
  - name: nginx
    version: 1.1.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
